version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: laravel_mysql_template
    # "no" ensures it stays shut down unless you manually run 'docker compose up'
    restart: "no" 
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend_network

volumes:
  mysql_data:
    driver: local

networks:
  backend_network:
    driver: bridge